"""empty message

Revision ID: 0aae85dff9cb
Revises: 5317befbe080
Create Date: 2020-12-13 17:42:09.904887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aae85dff9cb'
down_revision = '5317befbe080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_delete')
    # ### end Alembic commands ###
