"""empty message

Revision ID: 5317befbe080
Revises: d3aee6d1b2c3
Create Date: 2020-12-12 20:54:07.928472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5317befbe080'
down_revision = 'd3aee6d1b2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_signups', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('event_signups', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_signups', 'updated_at')
    op.drop_column('event_signups', 'created_at')
    # ### end Alembic commands ###
